ImHungry/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ImHungry.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ViewResult LoginForm()
        {
            return View();
        }
    }
}

ImHungry/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ImHungry.Models;

namespace ImHungry.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly ImHungryDBContext _context;

        public RestaurantsController(ImHungryDBContext context)
        {
            _context = context;
        }

        // GET: Restaurants
        public async Task<IActionResult> Index()
        {
            var imHungryDBContext = _context.Restaurants.Include(r => r.Category);
            return View(await imHungryDBContext.ToListAsync());
        }

        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.Category)
                .FirstOrDefaultAsync(m => m.RestId == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.RestaurantCategories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RestId,CategoryId,RestName,RestAddress,RestCity,RestZipcode,RestCountry,RestPhone")] Restaurants restaurants)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurants);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.RestaurantCategories, "CategoryId", "CategoryName", restaurants.CategoryId);
            return View(restaurants);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants.FindAsync(id);
            if (restaurants == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.RestaurantCategories, "CategoryId", "CategoryName", restaurants.CategoryId);
            return View(restaurants);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RestId,CategoryId,RestName,RestAddress,RestCity,RestZipcode,RestCountry,RestPhone")] Restaurants restaurants)
        {
            if (id != restaurants.RestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurants);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantsExists(restaurants.RestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.RestaurantCategories, "CategoryId", "CategoryName", restaurants.CategoryId);
            return View(restaurants);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurants = await _context.Restaurants
                .Include(r => r.Category)
                .FirstOrDefaultAsync(m => m.RestId == id);
            if (restaurants == null)
            {
                return NotFound();
            }

            return View(restaurants);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurants = await _context.Restaurants.FindAsync(id);
            _context.Restaurants.Remove(restaurants);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantsExists(int id)
        {
            return _context.Restaurants.Any(e => e.RestId == id);
        }
    }
}

ImHungry/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Hungry?";
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" href="css/styles.css"/>
    <title>Hungry?</title>
</head>
<body style="top: 0px; left: 0px; width: 1920px; height: 1080px; background: transparent linear-gradient(180deg, #FF7F00 0%, #FFB100 100%) 0% 0% no-repeat padding-box; opacity: 1;">
    <div class="container" style="top: 277px; left: 689px; width: 543px; height: 576px; background: #FF6767 0% 0% no-repeat padding-box; box-shadow: 0px 24px 35px #696969; border: 2px solid #FFFFFF; border-radius: 57px; opacity: 0.2;">
        <div class="table">
            <div class="text-lg-center" style="top: 349px; left: 800px; width: 320px; height: 95px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-80)/var(--unnamed-line-spacing-97) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 80px/97px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                Hungry?
            </div>
            <div class="btn" style="top: 493px; left: 824px; width: 275px; height: 83px; border: 2px solid #FFFFFF; border-radius: 49px; opacity: 1;">
                <a class="button" asp-action="LoginForm" style="font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                    Log In
                </a>
            </div>
            <div class="btn" style="top: 626px; left: 753px; width: 414px; height: 83px; border: 2px solid #FFFFFF; border-radius: 49px; opacity: 1;">
                <a asp-action="Index" asp-controller="Restaurants" style="top: 644px; left: 782px; width: 352px; height: 48px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                    Restaurants Nearby
                </a>
            </div>
            <div class="nav-link" style="top: 756px; left: 866px; width: 183px; height: 36px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-medium) 30px/37px var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; text-decoration: underline; font: normal normal medium 30px/37px Helvetica Neue; letter-spacing: 0px; color: #F8F8F8; opacity: 1;">
                Sign up here!
            </div>
        </div>
    </div>
</body>
</html>

ImHungry/Views/Home/LoginForm.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="css/styles.css" />
    <title>Hungry?</title>
</head>
<body style="top: 0px; left: 0px; width: 1920px; height: 1080px; background: transparent linear-gradient(180deg, #FF7F00 0%, #FFB100 100%) 0% 0% no-repeat padding-box; opacity: 1;">
    <div class="container" style="top: 277px; left: 689px; width: 543px; height: 576px; background: #FF6767 0% 0% no-repeat padding-box; box-shadow: 0px 24px 35px #696969; border: 2px solid #FFFFFF; border-radius: 57px; opacity: 0.2;">
        <div class="btn-block" style="top: 170px; left: 28px; width: 232px; height: 83px; background: #FF8D15 0% 0% no-repeat padding-box; border: 2px solid #FFFFFF; border-radius: 49px; opacity: 1;">
            <a asp-action="Index" asp-controller="Home" style="top: 188px; left: 65px; width: 159px; height: 48px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                Go back
            </a>
        </div>
        <div class="table" style="top: 277px; left: 689px; width: 543px; height: 576px; background: #FF6767 0% 0% no-repeat padding-box; box-shadow: 0px 24px 35px #00000064; border: 2px solid #FFFFFF; border-radius: 57px; opacity: 0.2;">
            <div class="text-lg-center" style="top: 298px; left: 821px; width: 280px; height: 168px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) 70px/85px var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: center; font: normal normal bold 70px/85px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                Who's Hungry?
            </div>
            <div class="form-text" style="top: 499px; left: 725px; width: 471px; height: 61px; background: #FFFFFF 0% 0% no-repeat padding-box; border: 2px solid #7C7C7C; border-radius: 10px; opacity: 1;">
                <a asp-action="Index" style="top: 506px; left: 755px; width: 196px; height: 48px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #7C7C7C; opacity: 0.4;">
                    Username
                </a>
            </div>
            <div class="form-text" style="top: 616px; left: 725px; width: 471px; height: 61px; background: #FFFFFF 0% 0% no-repeat padding-box; border: 2px solid #7C7C7C; border-radius: 10px; opacity: 1;">
                <a asp-action="Index" style="top: 623px; left: 755px; width: 189px; height: 48px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #7C7C7C; opacity: 0.4;">
                    Password
                </a>
            </div>
            <div class="btn" style="top: 714px; left: 774px; width: 374px; height: 83px; background: #FF8D15 0% 0% no-repeat padding-box; border: 2px solid #FFFFFF; border-radius: 49px; opacity: 1;">
                <a asp-action="Index" asp-controller="Restaurants" style="top: 732px; left: 873px; width: 167px; height: 48px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) var(--unnamed-font-size-40)/var(--unnamed-line-spacing-49) var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: left; font: normal normal bold 40px/49px Helvetica Neue; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
                    Let's Go!
                </a>
            </div>
            <div class="nav-link" style="top: 813px; left: 883px; width: 156px; height: 24px; font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-bold) 20px/25px var(--unnamed-font-family-helvetica-neue); letter-spacing: var(--unnamed-character-spacing-0); text-align: center; text-decoration: underline; font: normal normal bold 20px/25px Helvetica Neue; letter-spacing: 0px; color: #000000; opacity: 1;">
                Reset Password
            </div>
        </div>
    </div>
</body>
</html>